name: BQ Testing

on:
  pull_request:
    branches: [ main ]

jobs:
  test-bigquery-magics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout spanner-graph-notebook
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: python -m pip install build

      - name: Build spanner-graph-notebook
        run: python -m build

      - name: Checkout python-bigquery-magics
        uses: actions/checkout@v4
        with:
          repository: googleapis/python-bigquery-magics
          path: python-bigquery-magics

      - name: Install and test
        run: |
          set -e
          python -m venv venv
          . venv/bin/activate
          pip install pytest
      
          # Install spanner-graph-notebook in "editable" mode from its source directory.
          # This makes the source code directly importable by other packages in the same
          # environment, which is the standard way to handle local dependencies in CI.
          # This will also install all of its dependencies like 'portpicker'.
          pip install -e .
      
          # Now, install python-bigquery-magics. Since spanner-graph-notebook is already
          # available in the environment, pip will not try to download it again.
          pip install ./python-bigquery-magics
      
          pip install google-cloud-testutils
      
          # Change directory into the bigquery-magics checkout to run its tests.
          cd python-bigquery-magics
      
          # Run the tests. They should now be able to import spanner_graphs correctly.
          pytest -v tests/unit/test_graph_server.py tests/unit/bigquery/test_bigquery.py
