name: BQ Testing

on:
  pull_request:
    branches: [ main ]

jobs:
  test-bigquery-magics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout spanner-graph-notebook
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: python -m pip install build

      - name: Build spanner-graph-notebook
        run: python -m build

      - name: Checkout python-bigquery-magics
        uses: actions/checkout@v4
        with:
          repository: googleapis/python-bigquery-magics
          path: python-bigquery-magics

      - name: Diagnose Test Environment
        run: |
          set -e
          echo "--- Preparing Environment ---"
          python -m venv venv
          . venv/bin/activate
          pip install pytest build
      
          echo "--- Building Wheel ---"
          python -m build
      
          echo "--- Checking out python-bigquery-magics ---"
          git clone https://github.com/googleapis/python-bigquery-magics.git
          
          echo "--- Installing Dependencies ---"
          # Using the two-step install that you confirmed you used last
          pip install dist/*.whl
          pip install ./python-bigquery-magics
          pip install google-cloud-testutils
      
          # --- DIAGNOSTICS START ---
          echo "--- DIAGNOSTICS ---"
      
          echo "[Step 1] Checking executable paths..."
          which python
          which pip
      
          echo "\n[Step 2] Listing all installed packages..."
          pip freeze
      
          echo "\n[Step 3] Checking content of site-packages..."
          ls -lR venv/lib/python3.11/site-packages/ | grep "spanner" || echo "spanner-graph-notebook not found in site-packages"
      
          echo "\n[Step 4] Checking Python's import path..."
          python -c "import sys; from pprint import pprint; pprint(sys.path)"
      
          echo "\n[Step 5] Attempting a direct import..."
          python -c "from spanner_graphs import graph_visualization" && echo "==> Direct import of graph_visualization SUCCEEDED" || echo "==> Direct import of graph_visualization FAILED"
          python -c "import spanner_graphs" && echo "==> Direct import of spanner_graphs SUCCEEDED" || echo "==> Direct import of spanner_graphs FAILED"
      
          # --- DIAGNOSTICS END ---
      
          echo "\n--- Running Tests ---"
          cd python-bigquery-magics
          pytest -v tests/unit/test_graph_server.py tests/unit/bigquery/test_bigquery.py
