name: BQ Testing

on:
  pull_request:
    branches: [ main ]

jobs:
  test-bigquery-magics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout spanner-graph-notebook
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: python -m pip install build

      - name: Build spanner-graph-notebook
        run: python -m build

      - name: Checkout python-bigquery-magics
        uses: actions/checkout@v4
        with:
          repository: googleapis/python-bigquery-magics
          path: python-bigquery-magics
      
      - name: Install and test
        run: |
          set -e
          python -m venv venv
          . venv/bin/activate
          pip install pytest
      
          # We don't install the wheel directly. Instead, we'll tell pip to look
          # in the 'dist' directory when it resolves dependencies.
      
          # Install bigquery-magics and its extras.
          # The --find-links flag tells pip to look in the local dist/ directory
          # for packages before going to PyPI. This will make it pick up
          # the locally built wheel to satisfy the 'spanner-graph-notebook' dependency.
          pip install --find-links=dist ./python-bigquery-magics[spanner-graph-notebook]
      
          # The comment in the original file about removing the source directory to
          # prevent path conflicts was a good idea, but the command was incorrect.
          # This removes the 'spanner_graphs' source package directory.
          rm -rf spanner_graphs
      
          pip install google-cloud-testutils
      
          # Change directory into the bigquery-magics checkout
          cd python-bigquery-magics
      
          # Run the tests from within its own directory
          pytest -v tests/unit/test_graph_server.py tests/unit/bigquery/test_bigquery.py  
